// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// netLagCppLoop
NumericVector netLagCppLoop(IntegerMatrix mat, IntegerMatrix pdistmat, IntegerVector pathdist, NumericVector decay, NumericVector y, std::string normalization, bool reciprocal);
RcppExport SEXP tnam_netLagCppLoop(SEXP matSEXP, SEXP pdistmatSEXP, SEXP pathdistSEXP, SEXP decaySEXP, SEXP ySEXP, SEXP normalizationSEXP, SEXP reciprocalSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP );
        Rcpp::traits::input_parameter< IntegerMatrix >::type pdistmat(pdistmatSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type pathdist(pathdistSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type decay(decaySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< std::string >::type normalization(normalizationSEXP );
        Rcpp::traits::input_parameter< bool >::type reciprocal(reciprocalSEXP );
        NumericVector __result = netLagCppLoop(mat, pdistmat, pathdist, decay, y, normalization, reciprocal);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
