// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// netLagCppLoop
NumericVector netLagCppLoop(IntegerMatrix mat, IntegerMatrix pdistmat, IntegerVector pathdist, NumericVector decay, NumericVector y, std::string normalization, bool reciprocal);
RcppExport SEXP tnam_netLagCppLoop(SEXP matSEXP, SEXP pdistmatSEXP, SEXP pathdistSEXP, SEXP decaySEXP, SEXP ySEXP, SEXP normalizationSEXP, SEXP reciprocalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pdistmat(pdistmatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pathdist(pathdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type decay(decaySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type normalization(normalizationSEXP);
    Rcpp::traits::input_parameter< bool >::type reciprocal(reciprocalSEXP);
    rcpp_result_gen = Rcpp::wrap(netLagCppLoop(mat, pdistmat, pathdist, decay, y, normalization, reciprocal));
    return rcpp_result_gen;
END_RCPP
}
